/*
 *
 * BiduleOTron constants
 *
 */

export const GAME_STARTED = 'BOT/GAME_STARTED';
export const GAME_COMPLETED = 'BOT/GAME_COMPLETED';

export const PAD_UP = 'BOT/PAD_UP';
export const PAD_DOWN = 'BOT/PAD_DOWN';
export const PAD_LEFT = 'BOT/PAD_LEFT';
export const PAD_RIGHT = 'BOT/PAD_RIGHT';

export const PAD_SUBMIT = 'BOT/PAD_SUBMIT';
export const PAD_CANCEL = 'BOT/PAD_CANCEL';
export const PAD_MAILBOX = 'BOT/PAD_MAILBOX';

export const PIPE_ROTATE = 'BOT/PIPE_ROTATE';
export const PIPES_CHECK = 'BOT/PIPES_CHECK';

export const BUTTON_PRESSED = 'BOT/BUTTON_PRESSED';
export const BUTTON_SIMON_PRESSED = 'BOT/BUTTON_SIMON_PRESSED';

export const KEYPAD_INPUT = 'BOT/KEYPAD_INPUT';
export const FUSE_TOGGLE = 'BOT/FUSE_TOGGLE';
export const FUSES_CHECK = 'BOT/FUSES_CHECK';

export const WIRE_SELECT_TOP_SOCKET = 'BOT/WIRE_SELECT_TOP_SOCKET';
export const WIRE_SELECT_BOTTOM_SOCKET = 'BOT/WIRE_SELECT_BOTTOM_SOCKET';

export const SET_SCREEN = 'BOT/SET_SCREEN';
export const FOCUS_NEXT = 'BOT/FOCUS_NEXT';

export const MUSIC_TOGGLE = 'BOT/MUSIC_TOGGLE';
export const SFX_TOGGLE = 'BOT/SFX_TOGGLE';

export const SET_CONTROL_PANEL_FOCUS = 'BOT/SET_CONTROL_PANEL_FOCUS';
export const SHOW_POPUP = 'BOT/SHOW_POPUP';

export const COMPUTER_ON_OFF = 'BOT/COMPUTER_ON_OFF';
